"""DesignVersion and EngineeringDecision (doc 8.2, 8.3) - the immutable,
versioned engineering-object graph. A `DesignVersion` row is never UPDATEd
after creation (no service function in this codebase writes to its
genotype_manifest/status fields post-insert except the explicit, append-
only status lifecycle transition `proposed -> approved -> built -> tested
-> retired`, which is itself recorded as a new event, not a silent field
mutation) - see `harness/projects/service.py` for the only code path that
touches these rows.
"""
from __future__ import annotations

from sqlalchemy import JSON, Float, ForeignKey, Integer, String
from sqlalchemy.orm import Mapped, mapped_column

from harness.db import Base, guard_immutable_fields


class DesignVersion(Base):
    """doc 8.2. `parent_version_ids` is a JSON array (not a single FK) -
    the doc's own schema allows more than one parent (e.g. a merge of two
    prior lines), so a plain foreign key would under-model it. Comparison
    between two versions is done structurally by
    `harness/designs/genotype_diff.py` / `decision_diff.py`, never by
    diffing rendered report text."""

    __tablename__ = "design_versions"

    design_version_id: Mapped[str] = mapped_column(String, primary_key=True)
    project_id: Mapped[str] = mapped_column(ForeignKey("projects.project_id"), index=True)
    version_label: Mapped[str] = mapped_column(String)  # e.g. "strain_v1"
    parent_version_ids: Mapped[list] = mapped_column(JSON, default=list)
    branch_name: Mapped[str] = mapped_column(String, default="main")
    genotype_manifest: Mapped[dict] = mapped_column(JSON, default=dict)  # {baseline_strain, modifications: []}
    created_from_learning_cycle_id: Mapped[str | None] = mapped_column(String, default=None)
    rationale_snapshot_id: Mapped[str | None] = mapped_column(String, default=None)
    status: Mapped[str] = mapped_column(String, default="proposed")  # proposed|approved|built|tested|retired
    proposed_by: Mapped[str] = mapped_column(String)  # actor_id - required for proposer-cannot-self-approve
    created_at: Mapped[float] = mapped_column(Float)


class EngineeringDecision(Base):
    """doc 8.3 - persisted, DesignVersion-scoped counterpart of Problem 01's
    in-memory `harness.workflow.contracts.EngineeringDecision`. Kept as a
    genuinely separate representation (not a JSON blob of the pydantic
    object) so decisions are relationally queryable (lineage joins,
    `PortfolioView` grouping) - see `harness/designs/adapters.py` for the
    conversion between the two, exercised with round-trip tests."""

    __tablename__ = "engineering_decisions"

    decision_id: Mapped[str] = mapped_column(String, primary_key=True)
    design_version_id: Mapped[str] = mapped_column(ForeignKey("design_versions.design_version_id"), index=True)
    target: Mapped[str] = mapped_column(String)
    target_type: Mapped[str] = mapped_column(String, default="gene")  # gene|reaction|metabolite|regulatory_element|pathway
    operation: Mapped[str] = mapped_column(String)  # knockout|knockdown|overexpression|mutation|integration|promoter_tuning|other
    mechanism_hypothesis_ids: Mapped[list] = mapped_column(JSON, default=list)
    expected_effects: Mapped[list] = mapped_column(JSON, default=list)
    risks: Mapped[list] = mapped_column(JSON, default=list)
    evidence_ids: Mapped[list] = mapped_column(JSON, default=list)
    implementation_spec: Mapped[str] = mapped_column(String, default="")
    validation_spec: Mapped[str] = mapped_column(String, default="")
    confidence: Mapped[str] = mapped_column(String, default="low")  # high|medium|low
    approval_state: Mapped[str] = mapped_column(String, default="proposed")  # proposed|accepted|rejected|human_review
    source_run_id: Mapped[str | None] = mapped_column(String, default=None)  # Problem-01 WorkflowRun.run_id, if generated by it
    order_index: Mapped[int] = mapped_column(Integer, default=0)


# Only the explicit lifecycle status field may change post-creation on
# either table - genotype, decisions, and their content are immutable.
guard_immutable_fields(DesignVersion, mutable_fields={"status"})
guard_immutable_fields(EngineeringDecision, mutable_fields={"approval_state"})
