"""ProjectEvent type constants (doc 9.1's recommended list, plus a few this
implementation genuinely needs). Centralized so `replay_project` and every
service module agree on spelling.
"""
from __future__ import annotations

PROJECT_CREATED = "PROJECT_CREATED"
PROJECT_STATUS_CHANGED = "PROJECT_STATUS_CHANGED"
PROJECT_RENAMED = "PROJECT_RENAMED"
PROJECT_CONTEXT_UPDATED = "PROJECT_CONTEXT_UPDATED"
CYCLE_STATE_CHANGED = "CYCLE_STATE_CHANGED"
DESIGN_PROPOSED = "DESIGN_PROPOSED"
DESIGN_APPROVED = "DESIGN_APPROVED"
CONSTRUCT_REGISTERED = "CONSTRUCT_REGISTERED"
CONSTRUCT_STATUS_CHANGED = "CONSTRUCT_STATUS_CHANGED"
GENOTYPE_VERIFIED = "GENOTYPE_VERIFIED"
EXPERIMENT_PLANNED = "EXPERIMENT_PLANNED"
RUN_RECORDED = "RUN_RECORDED"
DATA_INGESTED = "DATA_INGESTED"
QC_COMPLETED = "QC_COMPLETED"
OBSERVATION_DERIVED = "OBSERVATION_DERIVED"
HYPOTHESIS_UPDATED = "HYPOTHESIS_UPDATED"
FAILURE_CLASSIFIED = "FAILURE_CLASSIFIED"
LEARNING_CYCLE_STARTED = "LEARNING_CYCLE_STARTED"
LEARNING_CYCLE_COMPLETED = "LEARNING_CYCLE_COMPLETED"
POLICY_UPDATE_PROPOSED = "POLICY_UPDATE_PROPOSED"
POLICY_UPDATE_APPROVED = "POLICY_UPDATE_APPROVED"
POLICY_UPDATE_REJECTED = "POLICY_UPDATE_REJECTED"
REDESIGN_CREATED = "REDESIGN_CREATED"
KNOWLEDGE_CLAIM_SUBMITTED = "KNOWLEDGE_CLAIM_SUBMITTED"
KNOWLEDGE_CLAIM_PROMOTED = "KNOWLEDGE_CLAIM_PROMOTED"
KNOWLEDGE_CLAIM_DEMOTED = "KNOWLEDGE_CLAIM_DEMOTED"
KNOWLEDGE_CLAIM_RETRACTED = "KNOWLEDGE_CLAIM_RETRACTED"
APPROVAL_RECORDED = "APPROVAL_RECORDED"

# User-authored idea capture ("sudden inspiration" entry point) - a
# free-text note kept in its own entity_type/table (harness/ideas/models.py)
# so it is never mixed into knowledge-base-derived content, but still
# written into the SAME ProjectEvent ledger as every other Problem.
PROJECT_IDEA_CAPTURED = "PROJECT_IDEA_CAPTURED"
PROJECT_IDEA_LINKED_TO_DESIGN = "PROJECT_IDEA_LINKED_TO_DESIGN"
PROJECT_IDEA_DISMISSED = "PROJECT_IDEA_DISMISSED"

# Problem 03 (Bottleneck Diagnosis Loop) - written into the SAME
# ProjectEvent ledger as Problems 01/02 (doc03 6.3's "no parallel,
# disconnected history store" rule), never a second store.
DIAGNOSIS_SESSION_STARTED = "DIAGNOSIS_SESSION_STARTED"
DIAGNOSIS_STATE_CHANGED = "DIAGNOSIS_STATE_CHANGED"
DIAGNOSIS_OBSERVATION_NORMALIZED = "DIAGNOSIS_OBSERVATION_NORMALIZED"
DIAGNOSIS_HYPOTHESIS_GENERATED = "DIAGNOSIS_HYPOTHESIS_GENERATED"
DIAGNOSIS_HYPOTHESIS_MERGED = "DIAGNOSIS_HYPOTHESIS_MERGED"
DIAGNOSIS_EVIDENCE_LINKED = "DIAGNOSIS_EVIDENCE_LINKED"
DIAGNOSIS_MODEL_RUN_RECORDED = "DIAGNOSIS_MODEL_RUN_RECORDED"
DIAGNOSIS_ASSESSMENT_RECORDED = "DIAGNOSIS_ASSESSMENT_RECORDED"
DIAGNOSIS_TEST_SELECTED = "DIAGNOSIS_TEST_SELECTED"
DIAGNOSIS_EXECUTION_PLAN_DRAFTED = "DIAGNOSIS_EXECUTION_PLAN_DRAFTED"
DIAGNOSIS_BELIEF_UPDATED = "DIAGNOSIS_BELIEF_UPDATED"
DIAGNOSIS_STOPPING_DECIDED = "DIAGNOSIS_STOPPING_DECIDED"
DIAGNOSIS_HUMAN_DECISION_RECORDED = "DIAGNOSIS_HUMAN_DECISION_RECORDED"
DIAGNOSIS_HANDED_OFF = "DIAGNOSIS_HANDED_OFF"

# Problem 04 (Engineering Design Generation and Decision Loop) - written into
# the SAME ProjectEvent ledger as Problems 01-03 (doc04 §6: every mutating
# design action must form a Memory Event; no separate/disconnected store).
DESIGN_PROJECT_CREATED = "DESIGN_PROJECT_CREATED"
DESIGN_WORKFLOW_STATE_CHANGED = "DESIGN_WORKFLOW_STATE_CHANGED"
DESIGN_HANDOFF_INGESTED = "DESIGN_HANDOFF_INGESTED"
DESIGN_HANDOFF_STALE = "DESIGN_HANDOFF_STALE"
DESIGN_STRATEGY_GENERATED = "DESIGN_STRATEGY_GENERATED"
DESIGN_STRATEGY_REJECTED = "DESIGN_STRATEGY_REJECTED"
DESIGN_CANDIDATE_GENERATED = "DESIGN_CANDIDATE_GENERATED"
DESIGN_CANDIDATE_REVISED = "DESIGN_CANDIDATE_REVISED"
DESIGN_CANDIDATE_REJECTED = "DESIGN_CANDIDATE_REJECTED"
DESIGN_CANDIDATE_SELECTED = "DESIGN_CANDIDATE_SELECTED"
DESIGN_PORTFOLIO_GENERATED = "DESIGN_PORTFOLIO_GENERATED"
DESIGN_PORTFOLIO_DECIDED = "DESIGN_PORTFOLIO_DECIDED"
DESIGN_EVALUATION_COMPLETED = "DESIGN_EVALUATION_COMPLETED"
DESIGN_COUNTERFACTUAL_RUN_RECORDED = "DESIGN_COUNTERFACTUAL_RUN_RECORDED"
DESIGN_BUILD_TEST_PACKAGE_DRAFTED = "DESIGN_BUILD_TEST_PACKAGE_DRAFTED"
DESIGN_HUMAN_DECISION_RECORDED = "DESIGN_HUMAN_DECISION_RECORDED"
DESIGN_BUILD_STATUS_CHANGED = "DESIGN_BUILD_STATUS_CHANGED"
DESIGN_OUTCOME_INGESTED = "DESIGN_OUTCOME_INGESTED"
DESIGN_VERSION_BRIDGED = "DESIGN_VERSION_BRIDGED"
DESIGN_NEXT_ITERATION_STARTED = "DESIGN_NEXT_ITERATION_STARTED"
DESIGN_DIAGNOSIS_REOPEN_REQUESTED = "DESIGN_DIAGNOSIS_REOPEN_REQUESTED"
DESIGN_LOOP_STOPPED = "DESIGN_LOOP_STOPPED"

# Problem 05 (Evaluator & Scientific Critic) - written into the SAME
# ProjectEvent ledger as Problems 01-04 (doc05 §9: every mutating
# evaluation/review/decision action must form a Memory Event; no separate/
# disconnected store, and never overwritten by a later round).
EVAL_CASE_OPENED = "EVAL_CASE_OPENED"
EVAL_STATE_CHANGED = "EVAL_STATE_CHANGED"
EVAL_CLAIMS_EXTRACTED = "EVAL_CLAIMS_EXTRACTED"
EVAL_DETERMINISTIC_CHECKS_RUN = "EVAL_DETERMINISTIC_CHECKS_RUN"
EVAL_EVIDENCE_ASSESSED = "EVAL_EVIDENCE_ASSESSED"
EVAL_MODEL_RECORDS_ASSESSED = "EVAL_MODEL_RECORDS_ASSESSED"
EVAL_SCIENTIFIC_REVIEW_COMPLETED = "EVAL_SCIENTIFIC_REVIEW_COMPLETED"
EVAL_CANDIDATE_VECTORS_COMPUTED = "EVAL_CANDIDATE_VECTORS_COMPUTED"
EVAL_META_REVIEW_DECIDED = "EVAL_META_REVIEW_DECIDED"
EVAL_REVISION_TASKS_CREATED = "EVAL_REVISION_TASKS_CREATED"
EVAL_REVISION_CYCLE_COMPLETED = "EVAL_REVISION_CYCLE_COMPLETED"
EVAL_HUMAN_DECISION_RECORDED = "EVAL_HUMAN_DECISION_RECORDED"
EVAL_RETURNED_TO_DIAGNOSIS = "EVAL_RETURNED_TO_DIAGNOSIS"
EVAL_MEMORY_EVENT_RECORDED = "EVAL_MEMORY_EVENT_RECORDED"

# Problem 06 (Predictive Simulation Loop & Virtual Cell Integration) -
# written into the SAME ProjectEvent ledger as Problems 01-05 (doc06's own
# "no parallel/disconnected history store" precedent, already established
# by every prior problem in this codebase).
VC_SIMULATION_CASE_OPENED = "VC_SIMULATION_CASE_OPENED"
VC_SIMULATION_STATE_CHANGED = "VC_SIMULATION_STATE_CHANGED"
VC_CELL_STATE_RECORDED = "VC_CELL_STATE_RECORDED"
VC_PERTURBATIONS_COMPILED = "VC_PERTURBATIONS_COMPILED"
VC_COMPATIBILITY_CHECKED = "VC_COMPATIBILITY_CHECKED"
VC_SIMULATION_RUN_RECORDED = "VC_SIMULATION_RUN_RECORDED"
VC_COMPARISON_COMPUTED = "VC_COMPARISON_COMPUTED"
VC_PREDICTION_REVIEWED = "VC_PREDICTION_REVIEWED"
VC_VALIDATION_PLANNED = "VC_VALIDATION_PLANNED"
VC_OBSERVATION_LINKED = "VC_OBSERVATION_LINKED"
VC_RESIDUAL_COMPUTED = "VC_RESIDUAL_COMPUTED"
VC_UPDATE_PROPOSED = "VC_UPDATE_PROPOSED"
VC_UPDATE_DECIDED = "VC_UPDATE_DECIDED"
VC_BENCHMARK_RECORDED = "VC_BENCHMARK_RECORDED"
VC_CALIBRATION_PROFILE_BUILT = "VC_CALIBRATION_PROFILE_BUILT"

# Unified Scientific Workflow Orchestrator (六大核心模块统一集成 prompt,
# Workstream 1) - written into the SAME ProjectEvent ledger as Problems
# 01-06; every row also carries `workflow_run_id`/`correlation_id` (columns
# `ProjectEvent` already declared but no prior module populated).
ORCH_RUN_CREATED = "ORCH_RUN_CREATED"
ORCH_PHASE_CHANGED = "ORCH_PHASE_CHANGED"
ORCH_GATE_DECIDED = "ORCH_GATE_DECIDED"
ORCH_MODULE_STARTED = "ORCH_MODULE_STARTED"
ORCH_MODULE_HANDOFF_RECORDED = "ORCH_MODULE_HANDOFF_RECORDED"
ORCH_PAUSED = "ORCH_PAUSED"
ORCH_RESUMED = "ORCH_RESUMED"
ORCH_BLOCKED = "ORCH_BLOCKED"
ORCH_HUMAN_DECISION_RECORDED = "ORCH_HUMAN_DECISION_RECORDED"
ORCH_RUN_COMPLETED = "ORCH_RUN_COMPLETED"
ORCH_RUN_FAILED = "ORCH_RUN_FAILED"

# Scientific Capability Adapters (六大核心模块统一集成 prompt, Workstream 2:
# LLM structured candidate generation for Problems 3-5 + evidence
# retrieval). Written into the SAME ProjectEvent ledger.
GEN_LLM_GENERATION_RECORDED = "GEN_LLM_GENERATION_RECORDED"
GEN_LLM_FALLBACK_USED = "GEN_LLM_FALLBACK_USED"
GEN_EVIDENCE_SEARCHED = "GEN_EVIDENCE_SEARCHED"
GEN_EVIDENCE_MATCH_COMPUTED = "GEN_EVIDENCE_MATCH_COMPUTED"
GEN_HALLUCINATED_REFERENCE_REJECTED = "GEN_HALLUCINATED_REFERENCE_REJECTED"

# Phase D (Virtual Cell missing requirements): Cross-Modal Consistency,
# multi-scenario/combination simulation, larger GEM adapter.
VC_CROSS_MODAL_REPORT_BUILT = "VC_CROSS_MODAL_REPORT_BUILT"
VC_SCENARIO_CAMPAIGN_RUN = "VC_SCENARIO_CAMPAIGN_RUN"
VC_COMBINATION_INTERVENTION_COMPILED = "VC_COMBINATION_INTERVENTION_COMPILED"
