"""Persistence + DOI-verification entry points for
`harness.evidence_retrieval`."""
from __future__ import annotations

from typing import Any

from sqlalchemy.orm import Session

from harness.evidence_retrieval.condition_matching import EvidenceSide, MatchContext, MatchResult, compute_match
from harness.evidence_retrieval.crossref_adapter import CrossrefEvidenceAdapter
from harness.evidence_retrieval.models import EvidenceMatchReport
from harness.ids import new_id, now
from harness.memory import event_types as et
from harness.memory.event_store import append_event
from harness.paper_extraction.rule_distillation import rules_citing_ddr_ids
from harness.projects.service import project_context_summary


def record_match_report(
    session: Session, *, project_id: str, query_context_ref: dict[str, Any], evidence_id: str, result: MatchResult, actor_id: str,
) -> EvidenceMatchReport:
    row = EvidenceMatchReport(
        match_report_id=new_id("EVMATCH"), project_id=project_id, query_context_ref=query_context_ref, evidence_id=evidence_id,
        organism_match=result.organism_match, strain_match=result.strain_match, genotype_match=result.genotype_match,
        medium_match=result.medium_match, condition_match=result.condition_match, timepoint_match=result.timepoint_match,
        intervention_match=result.intervention_match, measurement_match=result.measurement_match, directness=result.directness,
        transfer_risks=result.transfer_risks, overall_match_status=result.overall_match_status,
        downgrade_reasons=result.downgrade_reasons, created_at=now(),
    )
    session.add(row)
    session.flush()
    append_event(
        session, project_id=project_id, event_type=et.GEN_EVIDENCE_MATCH_COMPUTED, entity_type="EvidenceMatchReport",
        entity_id=row.match_report_id, payload={"evidence_id": evidence_id, "overall_match_status": result.overall_match_status, "downgrade_reasons": result.downgrade_reasons},
        actor_type="agent", actor_id=actor_id,
    )
    return row


def match_evidence_item(session: Session, *, project_id: str, query: MatchContext, evidence_item, actor_id: str) -> EvidenceMatchReport:
    """`evidence_item` is a `harness.diagnosis.models.EvidenceItem` row."""
    evidence_side = EvidenceSide(
        organism=evidence_item.organism, strain=evidence_item.strain, genotype=evidence_item.genotype,
        medium=(evidence_item.condition or {}).get("medium"), condition=evidence_item.condition or {},
        timepoint=evidence_item.time_ref, intervention=evidence_item.intervention, measurement=evidence_item.measurement,
        directness=evidence_item.directness,
    )
    result = compute_match(query, evidence_side)
    return record_match_report(session, project_id=project_id, query_context_ref=query.__dict__, evidence_id=evidence_item.evidence_item_id, result=result, actor_id=actor_id)


def assess_ddr_applicability(session: Session, *, project_id: str, ddr_record: dict[str, Any], project, actor_id: str) -> dict[str, Any]:
    """DDR -> current-project "Applicability Report" (老师 §Phase3:
    "适用范围/情境匹配报告" - a historical decision record's transferability
    to the project at hand, not a bare re-display of the paper).

    Reuses `compute_match`/`record_match_report` - the same engine and the
    same persisted `EvidenceMatchReport` table `match_evidence_item` uses
    for wet-lab `EvidenceItem`s - rather than building a second matching
    engine for DDRs (老师 §第一阶段: "如果已有实现：不要重复建设").

    A DDR record only carries `organism`/`host` as structured comparable
    fields (`knowledge/ddr_database/schema_v2.json`) - no strain/genotype/
    medium/condition/timepoint/intervention/measurement. Those 7 dimensions
    are passed through as `None` (-> "unknown") rather than guessed, and
    `compute_match` already turns "5+ unknown dimensions" into an explicit
    `insufficient_metadata` status with per-dimension `transfer_risks`
    ("X could not be compared (missing metadata)") - this *is* the "明确
    记录需要哪些数据后才能启用" the design doc asks for, generated by the
    existing engine rather than hand-written here.

    `target_product` overlap is assessed separately (both Project and DDR
    metadata carry it as a real field) and folded into the persisted
    report's `transfer_risks`/`downgrade_reasons` so it survives on the
    same audit trail, rather than inventing a new table column.
    """
    meta = ddr_record.get("metadata", {})
    ctx = project_context_summary(project)
    project_host, project_strain = ctx["host"], ctx["strain"]
    query = MatchContext(organism=project_host, strain=project_strain)
    evidence_side = EvidenceSide(organism=meta.get("organism") or meta.get("host"), directness="indirect")
    result = compute_match(query, evidence_side)

    project_product = (project.target_product or "").strip().lower()
    ddr_product = str(meta.get("target_product") or "").strip().lower()
    if not project_product or not ddr_product:
        product_match = "unknown"
    elif project_product == ddr_product or project_product in ddr_product or ddr_product in project_product:
        product_match = "match"
    else:
        product_match = "mismatch"
        result.downgrade_reasons = [*result.downgrade_reasons, f"target product differs: project wants {project_product!r}, this DDR is about {ddr_product!r}"]
        result.transfer_risks = [*result.transfer_risks, "target product mismatch - the underlying pathway/mechanism may not transfer"]

    missing_data = [f for f in ("strain", "genotype", "medium", "condition", "timepoint", "intervention", "measurement")
                    if not getattr(evidence_side, f, None)]

    report = record_match_report(
        session, project_id=project_id, evidence_id=ddr_record.get("ddr_id", ""), actor_id=actor_id,
        query_context_ref={"organism": project_host, "strain": project_strain, "target_product": project.target_product},
        result=result,
    )

    # Engineering-mechanism dimension (老师 §Phase3 Round 2: "Engineering:
    # 设计动作相似度"): a DDR's own decision_chain `design_action` codes
    # (e.g. "M3") are the actual mechanism/engineering-pattern
    # classification already recorded on the record - and any rule
    # distilled from this DDR (`rules_citing_ddr_ids`) is itself evidence
    # the DDR's mechanism generalizes beyond its own paper. Both are
    # reused, not re-derived (老师 §第一阶段: 不要重复建设).
    design_actions = sorted({
        step.get("design_action") for step in ddr_record.get("decision_chain", []) if step.get("design_action")
    })
    rule_ids = rules_citing_ddr_ids([ddr_record.get("ddr_id", "")])

    matching_factors = []
    if result.organism_match == "match":
        matching_factors.append(f"host organism matches ({project_host})")
    if product_match == "match":
        matching_factors.append(f"target product matches ({project.target_product})")
    if design_actions:
        matching_factors.append(f"engineering design action(s): {', '.join(design_actions)}")
    if rule_ids:
        matching_factors.append(f"generalized into transferable rule(s): {', '.join(rule_ids)}")

    if result.organism_match == "mismatch" or product_match == "mismatch":
        confidence = 0.15
    elif result.organism_match == "match" and product_match == "match":
        confidence = 0.85
    elif result.organism_match == "match" or product_match == "match":
        confidence = 0.5
    else:
        confidence = 0.2

    return {
        "match_report_id": report.match_report_id, "ddr_id": ddr_record.get("ddr_id", ""), "project_id": project_id,
        "organism_match": result.organism_match, "product_match": product_match,
        "overall_match_status": result.overall_match_status if product_match != "mismatch" else "condition_mismatch",
        "matching_factors": matching_factors, "transfer_risks": result.transfer_risks,
        "downgrade_reasons": result.downgrade_reasons, "missing_data_for_full_report": missing_data,
        "confidence": confidence, "design_actions": design_actions, "rule_ids": rule_ids,
    }


def verify_doi(session: Session, *, project_id: str, doi: str, actor_id: str) -> bool:
    """Real Crossref lookup. Returns False (never raises) for a
    fabricated/unresolvable DOI, and records the rejection as a
    `ProjectEvent` so a hallucinated reference leaves an audit trail rather
    than silently disappearing."""
    resolved = CrossrefEvidenceAdapter().resolve_doi(doi)
    if not resolved:
        append_event(
            session, project_id=project_id, event_type=et.GEN_HALLUCINATED_REFERENCE_REJECTED, entity_type="DOI",
            entity_id=doi, payload={"doi": doi, "reason": "Crossref could not resolve this DOI"}, actor_type="agent", actor_id=actor_id,
        )
    return resolved
