"""Build/resume the fixed ten source-first Skill07 annotation packages."""
from __future__ import annotations
import argparse, hashlib, json, shutil, sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:sys.path.insert(0,str(ROOT))
from harness.paper_extraction.gold_infrastructure import GOLD_ROOT,PACKAGES,SCHEMAS,atomic_write,now,read,sha

EXPECTED=['6d69baa813434a95b3a7e47b1532d728_1-s2.0-S1096717621001750-main','ae4bdbd7884c413cb3e583301872456b_17_sb0c00597','paper:71ab13883b209e2872f3','8eda54dbbce846d9a1eed4ab48f4138a_16_s41564-020-00793-9','bc1ff5664e6e43ee90e585a8d84032a2_15_msystems.00353-25','9bdff88f38d746db81b953793f928e4d_2021-祁老师','c7d6c4ca5bad4997b2197020e073bb98_gkac206','fa7c24b1f3cf4dc9b6c0bf70790dbe13_02 曾老师-色氨酸','0f67e4e6e3d54232a2bf5532bb6526c4_11_gkab735','07db8df7471d4db693632f10ccdc2254_13_ja0c12406']

def schemas():
    common={'type':'string','enum':['UNKNOWN','NOT_REPORTED','NOT_APPLICABLE','UNCERTAIN']}
    experiment={'$schema':'https://json-schema.org/draft/2020-12/schema','$id':'skill07-gold-experiment-v1','type':'object','required':['gold_experiment_id','benchmark_paper_id','paper_id','annotation_tier','review_state','experiment_title','experiment_role','experiment_granularity','biological_objects','intervention_or_design_action','trigger','conditions','implementation','controls','replicates','readouts','analysis','results','rationale','supported_alternatives','supported_rule','rule_scope','atomic_claim_ids','evidence_ids','critical_provenance','known_ambiguities','annotator_notes','created_by','created_at','updated_at','schema_version'],'properties':{'gold_experiment_id':{'type':'string','pattern':'^GOLD-P\\d{2}-E\\d{3}$'},'benchmark_paper_id':{'type':'string','pattern':'^GOLD-P\\d{2}$'},'paper_id':{'type':'string'},'annotation_tier':{'enum':['HUMAN_DRAFT','HUMAN_REVIEWED','ADJUDICATED_GOLD','FROZEN_GOLD']},'review_state':{'type':'string'},'experiment_title':{'type':'string'},'experiment_role':{'enum':['ENGINEERING_INTERVENTION','SCREENING','SELECTION','EVOLUTION','MEASUREMENT','CHARACTERIZATION','MECHANISTIC_VALIDATION','CAUSAL_VALIDATION','OPTIMIZATION','COMPARATIVE_VALIDATION','PRODUCTION_VALIDATION','OTHER','UNCERTAIN']},'experiment_granularity':{'enum':['ATOMIC_EXPERIMENT','EXPERIMENT_SERIES','CAMPAIGN','SUBEXPERIMENT','UNCERTAIN']},'parent_experiment_id':{'type':['string','null']},'iteration_or_stage':{},'relations':{'type':'array','items':{'type':'object','required':['relation','target_id'],'properties':{'relation':{'enum':['PART_OF','PRECEDES','FOLLOWS','ITERATION_OF','VALIDATES','MOTIVATES','COMPARES_WITH']},'target_id':{'type':'string'}}}},'biological_objects':{'type':'array','items':{'type':'object','required':['object_id','object_type','name','experimental_role'],'properties':{'object_id':{'type':'string'},'object_type':{'type':'string'},'name':{'type':'string'},'strain_or_host':{},'genotype':{},'construct':{},'parent_object':{},'experimental_role':{'type':'string'}}}},'intervention_or_design_action':{},'trigger':{},'conditions':{'type':'array'},'implementation':{},'controls':{'type':'array'},'replicates':{'type':'object'},'readouts':{'type':'array'},'analysis':{'type':'array'},'results':{'type':'array'},'rationale':{},'supported_alternatives':{'type':'array'},'supported_rule':{},'rule_scope':{},'atomic_claim_ids':{'type':'array','items':{'type':'string'}},'evidence_ids':{'type':'array','items':{'type':'string'}},'critical_provenance':{'type':'array'},'known_ambiguities':{'type':'array'},'annotator_notes':{'type':'string'},'created_by':{'type':'string'},'created_at':{'type':'string'},'updated_at':{'type':'string'},'schema_version':{'const':'1.0.0'},'origin_flags':{'type':'array'},'candidate_model_ids':{'type':'array'}},'additionalProperties':True}
    claim={'$schema':'https://json-schema.org/draft/2020-12/schema','$id':'skill07-gold-claim-v1','type':'object','required':['claim_id','gold_experiment_id','claim_type','subject','predicate','object_or_value','qualifiers','claim_text_normalized','epistemic_status','value_role','support_status','evidence_ids','criticality','review_state','known_ambiguity','provenance','annotation_tier'],'properties':{'claim_id':{'type':'string','pattern':'^GOLD-P\\d{2}-E\\d{3}-C\\d{3}$'},'gold_experiment_id':{'type':'string'},'claim_type':{'enum':['OBJECT_IDENTITY','INTERVENTION','CONDITION','CONTROL','REPLICATE','READOUT','ANALYSIS','MEASURED_RESULT','COMPARATIVE_RESULT','CAUSAL_RESULT','RATIONALE','ALTERNATIVE','MECHANISTIC_INTERPRETATION','RULE','SCOPE','NEGATIVE_RESULT','LIMITATION']},'subject':{},'predicate':{},'object_or_value':{},'qualifiers':{'type':'object'},'claim_text_normalized':{'type':'string'},'epistemic_status':{'enum':['DIRECTLY_REPORTED','DERIVED_FROM_REPORTED_VALUES','AUTHOR_INTERPRETATION','REVIEWER_INTERPRETATION','INFERRED','UNCERTAIN']},'value_role':{'enum':['IMPLEMENTED','MEASURED','CALCULATED','REPORTED_REFERENCE','THRESHOLD','UNKNOWN']},'support_status':{'enum':['SUPPORTED','PARTIALLY_SUPPORTED','UNSUPPORTED','UNCERTAIN']},'evidence_ids':{'type':'array'},'criticality':{'enum':['CRITICAL','MAJOR','MINOR']},'review_state':{'type':'string'},'known_ambiguity':{},'provenance':{'type':'object'},'annotation_tier':{'enum':['HUMAN_DRAFT','HUMAN_REVIEWED','ADJUDICATED_GOLD','FROZEN_GOLD']}},'additionalProperties':True}
    evidence={'$schema':'https://json-schema.org/draft/2020-12/schema','$id':'skill07-gold-evidence-v1','type':'object','required':['evidence_id','benchmark_paper_id','paper_id','source_document_id','source_attribution','anchor_text_or_fingerprint','quote_or_excerpt','evidence_scope','supports_claim_ids','support_type','support_strength','directness','resolution','availability','provenance','review_state','annotation_tier'],'properties':{'evidence_id':{'type':'string','pattern':'^GOLD-P\\d{2}-E\\d{3}-V\\d{3}$'},'benchmark_paper_id':{'type':'string'},'paper_id':{'type':'string'},'source_document_id':{'type':'string'},'source_attribution':{'type':'string'},'section':{},'paragraph_id':{},'page':{},'figure':{},'panel':{},'table':{},'supplement':{},'other_locator':{},'anchor_text_or_fingerprint':{'type':'string'},'quote_or_excerpt':{'type':'string','maxLength':500},'evidence_scope':{'enum':['TEXT_DIRECT','FIGURE','FIGURE_CAPTION','TABLE','METHODS','RESULTS','SUPPLEMENT','MULTI_ANCHOR']},'supports_claim_ids':{'type':'array'},'support_type':{'type':'string'},'support_strength':{'enum':['DIRECT','SUPPORTING_CONTEXT','INDIRECT','INSUFFICIENT']},'directness':{'type':'string'},'resolution':{'type':'string'},'availability':{'enum':['AVAILABLE','UNAVAILABLE','UNKNOWN']},'provenance':{'type':'object'},'review_state':{'type':'string'},'annotation_tier':{'enum':['HUMAN_DRAFT','HUMAN_REVIEWED','ADJUDICATED_GOLD','FROZEN_GOLD']}},'additionalProperties':True}
    SCHEMAS.mkdir(parents=True,exist_ok=True)
    for name,value in [('experiment',experiment),('claim',claim),('evidence',evidence)]:atomic_write(SCHEMAS/f'{name}.schema.json',value)

def main(resume=True):
    schemas(); manifest=read(ROOT/'skill07_wave2_baseline_manifest.json'); byid={d['paper_id']:d for d in manifest['documents']}; gold=read(ROOT/'skill07_gold_review.json'); alignment=read(ROOT/'skill07_semantic_alignment_report.json')
    review_by={p['benchmark_paper_id']:p for p in gold['papers']}; imported=additional=0
    for i,pid in enumerate(EXPECTED,1):
        bid=f'GOLD-P{i:02d}'
        if pid not in byid:raise FileNotFoundError(f'fixed core source missing: {bid} {pid}')
        d=byid[pid]; source_path=Path(d['clean_document_path']); source=read(source_path); package=PACKAGES/bid
        if package.exists() and not resume:raise FileExistsError(package)
        package.mkdir(parents=True,exist_ok=True)
        paragraphs=[{'paragraph_id':p.get('paragraph_id'),'section':p.get('section'),'text':p.get('text',''),'fingerprint':hashlib.sha256(p.get('text','').encode()).hexdigest()[:16]} for p in source.get('paragraphs',[])]
        source_index={'benchmark_paper_id':bid,'paper_id':pid,'source_document_path':str(source_path),'source_document_hash':d['clean_document_hash'],'paragraph_ids':[p['paragraph_id'] for p in paragraphs],'paragraphs':paragraphs,'figures':source.get('figures',[]),'tables':source.get('tables',[]),'supplements':'UNAVAILABLE' if not any('supp' in str(s).casefold() for s in source.get('sections',[])) else 'REFERENCED_REVIEW_REQUIRED'}
        atomic_write(package/'source_index.json',source_index)
        review=review_by.get(bid,{}); aids=[]
        for item in gold.get('review_items',[]):
            if item['paper_benchmark_id']==bid:aids.append(item)
        pair=next((x for x in alignment['pairs'] if x['paper_id']==pid),None)
        imported+=len(pair['differences']) if pair else 0
        candidates=[]
        for item in aids:
            for origin,key in [('A_ONLY','a_interpretation'),('G_ONLY','g_interpretation')]:
                val=item.get(key)
                if isinstance(val,dict):candidates.append({'candidate_id':item['item_id']+'-'+origin,'origin_flags':[origin,'SILVER_CANDIDATE'],'candidate':val,'truth_status':'UNREVIEWED'})
        # Full candidate inventory, not only disagreement list. It remains Silver.
        additional+=len(candidates)
        context={'benchmark_paper_id':bid,'paper_id':pid,'candidate_visibility_default':'HIDDEN_BLIND_SOURCE_FIRST','a_available':any('A_ONLY' in c['origin_flags'] for c in candidates),'g_available':any('G_ONLY' in c['origin_flags'] for c in candidates),'union_candidate_inventory':candidates,'semantic_alignment':pair,'review_accelerators':aids,'candidate_items_are_gold':False}
        atomic_write(package/'candidate_context.json',context)
        atomic_write(package/'manifest.json',{'benchmark_paper_id':bid,'paper_id':pid,'status':'AWAITING_HUMAN_ANNOTATION','source_linked':True,'created_at':now(),'source_coverage_review_complete':False,'candidate_count':len(candidates),'gold_experiment_count':0,'claim_count':0,'evidence_count':0,'freeze_eligible':False})
        checklist={'complete_source_inventory_reviewed':False,'source_coverage_review_complete':False,'objects_bound':False,'granularity_resolved':False,'critical_claims_evidenced':False,'independent_reviews_complete':False,'adjudication_complete':False,'validator_passed':False}
        atomic_write(package/'review_checklist.json',checklist)
        for role in ('ANNOTATOR_A','ANNOTATOR_B','ADJUDICATOR'):
            path=package/'annotations'/f'{role}.json'
            if not path.exists():atomic_write(path,{'benchmark_paper_id':bid,'paper_id':pid,'role':role,'annotator_id':'UNASSIGNED','annotation_tier':'UNANNOTATED','review_state':'AWAITING_HUMAN_ANNOTATION','revision':0,'source_coverage_review_complete':False,'experiments':[],'claims':[],'evidence':[],'decisions':[],'history':[],'created_at':now(),'updated_at':now()})
    atomic_write(GOLD_ROOT/'build_summary.json',{'packages':10,'fixed_mapping_valid':True,'wave2_unresolved_imported':imported,'union_candidate_items':additional,'gold_records_created':0,'status':'AWAITING_HUMAN_ANNOTATION'})
if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--no-resume',action='store_true');args=parser.parse_args();main(not args.no_resume)
